# -*- coding: utf-8 -*-
"""cleaned data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JPcw1FtfL8YRGk-AXXQDU-NBKOun1l2U
"""

# 1. Reload the original CSV into `data`
data = pd.read_csv("/content/Netflix_movies_and_tv_shows_clustering.csv")
print("Original missing values after reloading:")
print(data.isnull().sum())

# 2. Handle missing values
# Fill missing values in 'director', 'cast', 'country' with 'Unknown'
for col in ['director', 'cast', 'country']:
    data[col] = data[col].fillna('Unknown')

# Fill missing values in 'date_added' and 'rating' with their respective modes
data['date_added'] = data['date_added'].fillna(data['date_added'].mode()[0])
data['rating'] = data['rating'].fillna(data['rating'].mode()[0])

print("Missing values after handling (all should be 0, except for date_added if NaT were reintroduced):")
print(data.isnull().sum())

# 3. Remove duplicates
initial_rows_reprocessed = data.shape[0]
data.drop_duplicates(inplace=True)
final_rows_reprocessed = data.shape[0]

print(f"\nNumber of rows before removing duplicates (reprocessed): {initial_rows_reprocessed}")
print(f"Number of rows after removing duplicates (reprocessed): {final_rows_reprocessed}")
print(f"Number of duplicate rows removed (reprocessed): {initial_rows_reprocessed - final_rows_reprocessed}")

# 4. Convert 'date_added' to datetime (this step reintroduces 10 NaT values as previously observed)
data['date_added'] = pd.to_datetime(data['date_added'], format='mixed', errors='coerce')

print("\nData types after conversion (reprocessed):")
print(data.info())
print("\nNumber of unparseable dates (NaT values) after conversion (reprocessed):", data['date_added'].isna().sum())

# 5. Save the fully processed `data` to `Netflix_processed_data.csv`
data.to_csv('Netflix_processed_ok_data.csv', index=False)
print("\nFully processed data saved to 'Netflix_processed_ok_data.csv'")

# 6. Load the new CSV and check for missing values to confirm persistence
data_checked = pd.read_csv('Netflix_processed_ok_data.csv')
print("\nMissing values in newly loaded 'Netflix_processed_data.csv' (data_checked):")
print(data_checked.isnull().sum())

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Ensure 'date_added' is in datetime format before proceeding with analysis
data['date_added'] = pd.to_datetime(data['date_added'], format='mixed', errors='coerce')

# Distribution of 'type' (Movie vs. TV Show)
plt.figure(figsize=(4, 2))
sns.countplot(x='type', data=data, hue='type', palette='viridis', legend=False)
plt.title('Distribution of Content Types')
plt.xlabel('Type')
plt.ylabel('Count')
plt.show()

# Top 10 ratings distribution
plt.figure(figsize=(10, 4))
sns.countplot(y='rating', data=data, hue='rating', order=data['rating'].value_counts().index[:10], palette='magma', legend=False)
plt.title('Top 10 Content Ratings Distribution')
plt.xlabel('Count')
plt.ylabel('Rating')
plt.show()

# Content added over time
data['year_added'] = data['date_added'].dt.year
plt.figure(figsize=(10, 4))
sns.countplot(x='year_added', data=data, hue='year_added', palette='coolwarm', legend=False)
plt.title('Number of Content Titles Added Over Years')
plt.xlabel('Year Added')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()